### ISSUE TITLE
Error when using zip.js 2.8 with TypeScript: Property `getData` does not exist on type `DirectoryEntry`

### ISSUE THREAD

**Issue by pewinski** [gildas-lormeau/zip.js#601]
Our project uses Typescript and Angular.

After updating to 2.8, new error occurs:

`TS2339: Property getData does not exist on type Entry`.

The snippet is:

```
  private unzipZipBlob = async (zippedBlob: Blob) => {
    const zipFileReader = new BlobReader(zippedBlob);
    const stream = new TransformStream();
    const response = new Response(stream.readable).blob();
    const zipReader = new ZipReader(zipFileReader);
    const firstEntry = (await zipReader.getEntries()).shift();
    if (!firstEntry || !firstEntry.getData) {
      throw new Error(...);
    }
    await firstEntry.getData(stream.writable);
    await zipReader.close();
    const unzippedBlob = await response;

    return unzippedBlob;
  };
```

It works fine with 2.7

I believe it is a bug, since the project follows semantic versioning. If not, could you please release the change withing next major version instead? A changelog would be also very useful.
